-- SwimXpert: Account / SwimmerProfile / ClientStatus migration (DRAFT FOR REVIEW)
-- Not applied via `dotnet ef database update` yet.
-- This repo also applies the same changes idempotently in Program.cs at startup.
--
-- Existing data notes:
--   * Users / Swimmers / Attendances already exist in Railway Postgres.
--   * Swimmers rows become "profiles" (children OR account holder). IsAccountHolder defaults false.
--   * Booking remains Attendances.SwimmerId (no table rename) — SwimmerProfileId ≡ SwimmerId.
--   * IsApproved default true; existing false rows keep false but no longer gate dashboard/booking submit.
--
-- FLAG(Booking=Child) — remaining child-shaped assumptions (intentional keep for now):
--   * Angular AuthService still uses `children: Child[]` as the local model for swimmer profiles.
--   * Guest booking lead payload still uses childName/childAge/childLevel field keys (API lead shape).
--   * ParentUserId / ParentUser navigation property names on Swimmer (account owner, not always a parent).
--
-- Review this, then either:
--   A) Deploy API (Program.cs ALTERs run automatically), or
--   B) Run this SQL manually against Postgres, then deploy.

BEGIN;

ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "ClientStatus" character varying(20) NOT NULL DEFAULT 'New';
ALTER TABLE "Users" ALTER COLUMN "IsApproved" SET DEFAULT true;

ALTER TABLE "Swimmers" ADD COLUMN IF NOT EXISTS "IsAccountHolder" boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS "LegacyClients" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PhoneNormalized" character varying(32) NOT NULL,
    "DisplayName" character varying(255),
    "Source" character varying(64),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_LegacyClients_PhoneNormalized"
    ON "LegacyClients" ("PhoneNormalized");

CREATE INDEX IF NOT EXISTS "IX_Swimmers_ParentUserId_IsAccountHolder"
    ON "Swimmers" ("ParentUserId", "IsAccountHolder");

COMMIT;
