using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using SwimXpert.Api.Data;
using SwimXpert.Api.Models;
using System.Text;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();
builder.Services.AddOpenApi();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Name = "Authorization",
        Type = SecuritySchemeType.Http,
        Scheme = "bearer",
        BearerFormat = "JWT",
        In = ParameterLocation.Header,
        Description = "Enter: Bearer {your JWT token}"
    });

    options.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference
                {
                    Type = ReferenceType.SecurityScheme,
                    Id = "Bearer"
                }
            },
            []
        }
    });
});

builder.Services.AddCors(options =>
{
    options.AddPolicy("AngularApp", policy =>
    {
        policy.WithOrigins("http://localhost:4200")
            .AllowAnyHeader()
            .AllowAnyMethod();
    });
});

var connectionString = builder.Configuration.GetConnectionString("DefaultConnection")
    ?? throw new InvalidOperationException("ConnectionStrings:DefaultConnection is missing.");

builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseNpgsql(connectionString));

var jwtKey = builder.Configuration["Jwt:Key"] ?? throw new InvalidOperationException("Jwt:Key is missing.");
var jwtIssuer = builder.Configuration["Jwt:Issuer"] ?? throw new InvalidOperationException("Jwt:Issuer is missing.");
var jwtAudience = builder.Configuration["Jwt:Audience"] ?? throw new InvalidOperationException("Jwt:Audience is missing.");
var signingKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey));

builder.Services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
})
.AddJwtBearer(options =>
{
    options.RequireHttpsMetadata = false;
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidateAudience = true,
        ValidateLifetime = true,
        ValidateIssuerSigningKey = true,
        ValidIssuer = jwtIssuer,
        ValidAudience = jwtAudience,
        IssuerSigningKey = signingKey,
        ClockSkew = TimeSpan.Zero
    };
});

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseCors("AngularApp");
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();

using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
    db.Database.EnsureCreated();
    db.Database.ExecuteSqlRaw("ALTER TABLE \"Swimmers\" ADD COLUMN IF NOT EXISTS \"ProfilePictureUrl\" character varying(500);");
    db.Database.ExecuteSqlRaw("ALTER TABLE \"Swimmers\" ADD COLUMN IF NOT EXISTS \"SkillProgressJson\" text NOT NULL DEFAULT '{{}}';");
    db.Database.ExecuteSqlRaw("""
        CREATE TABLE IF NOT EXISTS "LeadCaptures" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Name" character varying(150) NOT NULL,
            "Email" character varying(200),
            "Phone" character varying(30),
            "SourcePage" character varying(200),
            "SourceAction" character varying(200),
            "UserAgent" character varying(400),
            "IsContacted" boolean NOT NULL DEFAULT FALSE,
            "ContactedAt" timestamp with time zone,
            "CreatedAt" timestamp with time zone NOT NULL
        );
    """);
    db.Database.ExecuteSqlRaw("ALTER TABLE \"LeadCaptures\" ADD COLUMN IF NOT EXISTS \"IsContacted\" boolean NOT NULL DEFAULT FALSE;");
    db.Database.ExecuteSqlRaw("ALTER TABLE \"LeadCaptures\" ADD COLUMN IF NOT EXISTS \"ContactedAt\" timestamp with time zone;");
    db.Database.ExecuteSqlRaw("CREATE INDEX IF NOT EXISTS \"IX_LeadCaptures_CreatedAt\" ON \"LeadCaptures\" (\"CreatedAt\");");

    if (!db.Users.Any(u => u.Email == "admin@swimxpert.com"))
    {
        db.Users.Add(new User
        {
            Email = "admin@swimxpert.com",
            Password = BCrypt.Net.BCrypt.HashPassword("admin123"),
            FullName = "SwimXpert Admin",
            Role = "Admin",
            CreatedAt = DateTime.UtcNow
        });
        db.SaveChanges();
    }
}

app.Run();
