-- SwimXpert startup schema (Program.cs)
-- Order respects foreign keys. Run on empty DB after this script; EnsureCreatedAsync is replaced by explicit core tables below.

-- =============================================================================
-- 1. Core tables (equivalent to EnsureCreatedAsync from ApplicationDbContext)
-- =============================================================================

CREATE TABLE IF NOT EXISTS "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Email" character varying(255) NOT NULL,
    "Password" character varying(255) NOT NULL,
    "FullName" character varying(255) NOT NULL,
    "Role" character varying(50) NOT NULL DEFAULT 'Parent',
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamp with time zone NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email" ON "Users" ("Email");

CREATE TABLE IF NOT EXISTS "Swimmers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ParentUserId" integer NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "Name" character varying(150) NOT NULL,
    "Age" integer NOT NULL,
    "Level" integer NOT NULL DEFAULT 1,
    "CreatedAt" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_Swimmers_ParentUserId" ON "Swimmers" ("ParentUserId");

CREATE TABLE IF NOT EXISTS "TrainingSessions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title" character varying(200) NOT NULL,
    "StartTime" timestamp with time zone NOT NULL,
    "EndTime" timestamp with time zone NOT NULL,
    "Capacity" integer NOT NULL DEFAULT 10,
    "Status" character varying(30) NOT NULL DEFAULT 'Scheduled',
    "CreatedAt" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "Attendances" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SwimmerId" integer NOT NULL REFERENCES "Swimmers"("Id") ON DELETE CASCADE,
    "TrainingSessionId" integer NOT NULL REFERENCES "TrainingSessions"("Id") ON DELETE CASCADE,
    "SessionDate" timestamp with time zone NOT NULL,
    "IsPresent" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_Attendances_SwimmerId" ON "Attendances" ("SwimmerId");
CREATE INDEX IF NOT EXISTS "IX_Attendances_TrainingSessionId" ON "Attendances" ("TrainingSessionId");

CREATE TABLE IF NOT EXISTS "Payments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "Amount" numeric NOT NULL,
    "PaymentDate" timestamp with time zone NOT NULL,
    "Method" character varying(30) NOT NULL DEFAULT 'Cash',
    "Status" character varying(30) NOT NULL DEFAULT 'Completed',
    "Reference" character varying(100)
);
CREATE INDEX IF NOT EXISTS "IX_Payments_UserId" ON "Payments" ("UserId");

-- =============================================================================
-- 2. ALTER TABLE "Swimmers" (Program.cs)
-- =============================================================================
ALTER TABLE "Swimmers" ADD COLUMN IF NOT EXISTS "ProfilePictureUrl" character varying(500);
ALTER TABLE "Swimmers" ADD COLUMN IF NOT EXISTS "SkillProgressJson" text NOT NULL DEFAULT '{}';

-- =============================================================================
-- 3. LeadCaptures (Program.cs)
-- =============================================================================
CREATE TABLE IF NOT EXISTS "LeadCaptures" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" character varying(150) NOT NULL,
    "Email" character varying(200),
    "Phone" character varying(30),
    "SourcePage" character varying(200),
    "SourceAction" character varying(200),
    "UserAgent" character varying(400),
    "IsContacted" boolean NOT NULL DEFAULT false,
    "ContactedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL
);
ALTER TABLE "LeadCaptures" ADD COLUMN IF NOT EXISTS "IsContacted" boolean NOT NULL DEFAULT false;
ALTER TABLE "LeadCaptures" ADD COLUMN IF NOT EXISTS "ContactedAt" timestamp with time zone;
CREATE INDEX IF NOT EXISTS "IX_LeadCaptures_CreatedAt" ON "LeadCaptures" ("CreatedAt");

-- =============================================================================
-- 4. ProgressEntries (Program.cs) — FK to Swimmers
-- =============================================================================
CREATE TABLE IF NOT EXISTS "ProgressEntries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SwimmerId" integer NOT NULL REFERENCES "Swimmers"("Id") ON DELETE CASCADE,
    "EntryDate" timestamp with time zone NOT NULL,
    "Level" integer NOT NULL,
    "Notes" character varying(1000) NOT NULL DEFAULT '',
    "SkillsJson" text NOT NULL DEFAULT '[]',
    "CreatedAt" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_ProgressEntries_SwimmerId" ON "ProgressEntries" ("SwimmerId");

-- =============================================================================
-- 5. QuizResults (Program.cs) — FK to Users
-- =============================================================================
CREATE TABLE IF NOT EXISTS "QuizResults" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "Score" integer NOT NULL,
    "TotalQuestions" integer NOT NULL,
    "Percentage" integer NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_QuizResults_UserId" ON "QuizResults" ("UserId");

-- =============================================================================
-- 6. ALTER TABLE "Users" (Program.cs)
-- =============================================================================
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "EmailVerified" boolean NOT NULL DEFAULT true;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "EmailVerificationTokenHash" character varying(64);
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "EmailVerificationTokenExpiry" timestamp with time zone;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "FailedLoginAttempts" integer NOT NULL DEFAULT 0;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "LockoutUntil" timestamp with time zone;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "PasswordResetTokenHash" character varying(64);
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "PasswordResetTokenExpiry" timestamp with time zone;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "TwoFactorEnabled" boolean NOT NULL DEFAULT false;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "TwoFactorSecret" character varying(256);

-- =============================================================================
-- 7. RefreshTokens (Program.cs) — FK to Users
-- =============================================================================
CREATE TABLE IF NOT EXISTS "RefreshTokens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "TokenHash" character varying(64) NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "RevokedAt" timestamp with time zone,
    "ReplacedByTokenHash" character varying(64)
);
CREATE INDEX IF NOT EXISTS "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_RefreshTokens_TokenHash" ON "RefreshTokens" ("TokenHash");

-- =============================================================================
-- 8. AuditLogs (Program.cs) — no FK constraint
-- =============================================================================
CREATE TABLE IF NOT EXISTS "AuditLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AdminUserId" integer NOT NULL,
    "AdminEmail" character varying(255) NOT NULL,
    "Action" character varying(100) NOT NULL,
    "TargetType" character varying(100),
    "TargetId" character varying(50),
    "Details" text,
    "Timestamp" timestamp with time zone NOT NULL,
    "IpAddress" character varying(45)
);
CREATE INDEX IF NOT EXISTS "IX_AuditLogs_Timestamp" ON "AuditLogs" ("Timestamp");
CREATE INDEX IF NOT EXISTS "IX_AuditLogs_Action" ON "AuditLogs" ("Action");

-- =============================================================================
-- 9. ALTER TABLE "TrainingSessions" (Program.cs)
-- =============================================================================
ALTER TABLE "TrainingSessions" ADD COLUMN IF NOT EXISTS "PoolLocation" character varying(200);
